### PR TITLE
Name search via TCP and put >16kB

### PR DESCRIPTION
**Pull request by mdavidsaver**
A collection of changes

* Fix up a test failure
* Support PV name search over TCP
* Send correct version number to peer in VERSION message
* Support put with payload size greater than 16kB

Configuration of the the TCP name server list is done through a new property key name ".name_servers".

There will be some log spam if/when a name server loses connection.

### CODE REVIEW

**Comment by shroffk** [comment]
@mdavidsaver 
Sorry, but could you do a pull rebase of your branch on the master...that way you will get the new travis file and the PR will then have build and test results

**Comment by shroffk** [comment]
I have merged a fix, a rebase should result in the build succeeding again.

**Comment by mdavidsaver** [comment]
travis-ci is showing build failures related to "-source 1.4".  This seems a little old...

**Comment by shroffk** [comment]
yes, very old...I fixed it here
https://github.com/epics-base/caj/pull/7

**Pull request merged**
